import Image from "next/image";

import styles from "./About.module.css";

import Background from "@/components/bg";

import { headingFont, paragraphFont } from "@/lib/fonts";

const ImageHolster = ({ src, description, alt, title, ...props }) => {
  return (
    <div className="w-full aspect-[9/16] bg-cover relative rounded-2xl p-2 bg-color-5">
      <Image
        src={src}
        alt={alt ? alt : description}
        fill
        className={`rounded-2xl ${props.className && props.className}`}
        {...props}
      />
      <div
        className={`absolute bottom-0 left-0 p-3 pt-12 ${styles.background} rounded-b-2xl`}
      >
        <p>{description}</p>
        <span className={`${headingFont.className} text-2xl font-bold`}>
          {title}
        </span>
      </div>
    </div>
  );
};

export default function About() {
  return (
    <>
      <Background/>
      <main className="md:px-5 flex lg:flex-row flex-col justify-center items-center w-full h-[calc(100vh-4rem)]">
        <div className="flex-1 h-full flex flex-col justify-center">
          <h1
            className={`${headingFont.className} text-9xl md:text-5xl text-color-1`}
          >
            About Me
          </h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>
        <div className="flex-1 flex gap-5 h-full overflow-x-scroll">
          <ImageHolster
            src="/images/Boston-City-Photos-1.jpg"
            description={
              "lorem ipsum sit ammet lorem ipsum sit ammet lmaaaa aaa asdfsd fsdf "
            }
            title={"Lorme lorem lorem lorem lorem"}
          />
          <ImageHolster
            src="/images/Boston-City-Photos-19.jpg"
            description={
              "lorem ipsum sit ammet lorem ipsum sit ammet lmaaaa aaa asdfsd fsdf "
            }
            title={"Lorme lorem lorem lorem lorem"}
          />
          <ImageHolster
            src="/images/Boston-City-Photos-3.jpg"
            description={
              "lorem ipsum sit ammet lorem ipsum sit ammet lmaaaa aaa asdfsd fsdf "
            }
            title={"Lorme lorem lorem lorem lorem"}
          />
        </div>
      </main>
    </>
  );
}

export const metadata = {
  title: "John Tan-Aristy | About",
  description: "Generated by create next app",
};
