import Background from "@/components/bg";

export default function Work(){
    return (
        <>
            <Background/>
            <main>
                
            </main>
        </>
    )
}
export const metadata = {
    title: "Work | John Tan-Aristy",
    description: "Generated by create next app",
  };