import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "John Tan-Aristy | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-color-3 flex justify-center items-center text-color-5`}
      >
        <div className="w-full h-full min-h-screen max-w-screen-2xl">
          <Navbar />

          {children}
        </div>
      </body>
    </html>
  );
}
